### PR TITLE
ensure_dirs() cleanup

### PR DESCRIPTION
**Pull request by mgorny**
Far from a perfect solution but fixes at least some of the issues in #14. Long story short, removes the logic for altering permission on existing dirs, and fixes the 'weird' chown() to be more useful. Still not sure if that was the original intent though.

### CODE REVIEW

**Comment by radhermit** [comment]
@ferringb would be the best person to comment on original intent.

**Comment by mgorny** [comment]
So what do we do now?

**Comment by radhermit** [comment]
I'm planning to merge it hopefully this weekend, got sidetracked the past week updating snakeoil for the upcoming pychroot and other releases.

**Comment by radhermit** [comment]
Merged and added some more tests for ensure_dirs().

**Pull request closed without merging**
