### PR TITLE
Handle missing pypy3 object methods gracefully

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by mgorny** [comment]
Hmm, I need a different approach, you're actually using it in tests ;-).

**Comment by mgorny** [comment]
Ok, this should be better. I've also fixed `ignore_missing=True` in `steal_docs`.

**Comment by radhermit** [comment]
If your goal of these pull requests is to make pypy3 support work, I'd rather they were all in a single pull request with one of the changes being pypy3 CI support added and all tests passing. As I personally don't use pypy anywhere I can't easily test it and also don't currently care much about supporting it.

**Comment by mgorny** [comment]
Feel free to steal the second commit then. There's still lot of work to be done before tests pass. In particular, it seems that snakeoil does the horrible mistake of relying on `del` a lot.

**Comment by radhermit** [comment]
Merged the steal_docs() fix. The rest I'm not overly interested in since pypy hasn't historically kept up to CPython version compatibility as fast as snakeoil and pkg* drops it, e.g. I think pypy is currently at 3.7 and snakeoil requires a minimum of 3.8.

**Pull request closed without merging**
